"""OGC201, beyond its own examples."""

from openglcontext_checks.engine import check_source


def _found(source):
    return check_source(source, codes=['OGC201'])


def test_a_bare_pragma_is_told_to_name_its_codes():
    (bare_noqa,) = _found('import os  # noqa\n')
    assert (bare_noqa.line, bare_noqa.column) == (1, 12)
    assert bare_noqa.message.startswith('bare # noqa names no code')
    (bare_ignore,) = _found('x = f()  # type: ignore because\n')
    assert bare_ignore.message.startswith('bare # type: ignore names no code')


def test_an_unreasoned_pragma_is_told_to_give_its_reason():
    (finding,) = _found('import os  # noqa: F401, E402\n')
    assert finding.message.startswith('# noqa: F401, E402 gives no reason')
    (finding,) = _found('x = f()  # type: ignore[attr-defined, union-attr]\n')
    assert finding.message.startswith('# type: ignore[attr-defined, union-attr] gives no reason')


def test_its_own_finding_can_be_suppressed_with_a_reason_beside_it():
    source = 'x = f()  # type: ignore[x]  # noqa: OGC201 generated by a tool we do not own\n'
    assert _found(source) == []


def test_text_after_a_type_ignore_is_told_to_move_behind_a_hash():
    (finding,) = _found('x = f()  # type: ignore[attr-defined] the stubs lack it\n')
    assert (finding.line, finding.column) == (1, 10)
    assert finding.message.startswith(
        'mypy rejects text after # type: ignore[attr-defined]'
    )
    assert _found('x = f()  # type: ignore[attr-defined]  # the stubs lack it\n') == []
